[project]
name = "sjtushark"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "scapy>=2.6.1",
    "pyparsing>=3.0.0",
    "beautifulsoup4>=4.13.4",
]
